### PR TITLE
Random generation with MonadGen.

### PR DESCRIPTION
**Pull request by matthewleon**

### CODE REVIEW

**Comment by zaquest** [comment]
I don't think it's a good idea to add a dependency on `purescript-gen`. I don't see other number libraries including these instances either. And the PR is inclomplete as it doesn't update dependencies in `bower.json`, but that's minor.

**Comment by matthewleon** [comment]
I think the reason you're not seeing it elsewhere is because `purescript-gen` is quite new. Otherwise, large swaths of core are being updated to support it.

That said, I understand your hesitation with adding a new dependency.

**Comment by matthewleon** [comment]
On second thought, I believe the reason I didn't add the dep is because this package is already transitively dependent on it through `maybe`. I've never really been clear on what best practice is with transitive deps, but it seems that core packages are happy to leave them unspecified.

**Comment by zaquest** [comment]
It depends on `purescript-gen` through `purescript-quickcheck` which is a dev-only dependency. If `purescript-gen` was a slim dependency it'd bothered me less, but none of it's 5 dependencies is needed for `purescript-uint`, and there's probably more if we go recursively through it's dependencies.  I'm not sure how to proceed from here because `purescript` organization's packages either include it's instances in `purescript-gen` or if a package already depends on `purescript-gen` they include it in that packages. And these packages that depend on `purescript-gen` seem to be utility functions packages for one or another datatype, which are pretty much intended for such use. I'll investigate more about what's considered a good practice in purescript and try to come up with some solution.

**Comment by matthewleon** [comment]
I see your point. Makes sense.

**Pull request closed without merging**
